#!/usr/bin/env node
// Builds polymer-xref.js: which polymers in the search library also appear in
// the thermal (DSC/TGA/DMA) and chain-dimension datasets.
//
// The point is that a result card only offers "see its thermogram" when there
// IS one. A link that lands on a tool and then says "not in this library" is
// worse than no link, and the alternative - loading a 200 KB thermal library
// on the search page just to decide whether to draw an anchor - is not worth
// paying on every visit. This precomputes the answer into a few KB.
//
// Run: node scripts/build-xref.js         (writes the file)
//      node scripts/build-xref.js --check (CI: fails if it is out of date)

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
function load(file) {
  const sandbox = { window: {} };
  new Function('window', fs.readFileSync(path.join(ROOT, file), 'utf8')).call(sandbox, sandbox.window);
  return sandbox.window;
}

const polymers = load('polymer-data.js').POLYMER_DB;
const thermal = load('thermal-library.js').THERMAL_LIBRARY;
const chain = load('chain-data.js').CHAIN_DATA;

// Names are written differently across the three files - "Poly(lactide)" in one
// and "PLA" or "Polylactic acid" in another - so match on a stripped form and
// on every alias each side offers.
function norm(s) {
  return String(s || '').toLowerCase().replace(/[^a-z0-9]/g, '');
}
function keysOf(entry) {
  const out = [norm(entry.name)];
  if (entry.abbr) out.push(norm(entry.abbr));
  (entry.aka || []).forEach(a => out.push(norm(a)));
  return out.filter(Boolean);
}

function indexBy(list) {
  const map = new Map();
  list.forEach(e => keysOf(e).forEach(k => { if (!map.has(k)) map.set(k, e.id); }));
  return map;
}

const thermalIdx = indexBy(thermal);
const chainIdx = indexBy(chain);

const xref = {};
let tHits = 0, cHits = 0;
polymers.forEach(p => {
  const keys = keysOf(p);
  let t = null, c = null;
  for (const k of keys) {
    if (!t && thermalIdx.has(k)) t = thermalIdx.get(k);
    if (!c && chainIdx.has(k)) c = chainIdx.get(k);
  }
  if (!t && !c) return;
  const rec = {};
  if (t) { rec.t = t; tHits++; }
  if (c) { rec.c = c; cHits++; }
  xref[p.name] = rec;
});

const body = '// GENERATED by scripts/build-xref.js - do not edit by hand.\n' +
  '// Which search-library polymers also have thermal (t) and chain-dimension (c)\n' +
  '// data, so a result card can link only where the target actually has them.\n' +
  'window.POLYMER_XREF = ' + JSON.stringify(xref, null, 0) + ';\n';

const outPath = path.join(ROOT, 'polymer-xref.js');
if (process.argv.includes('--check')) {
  const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : '';
  if (current !== body) {
    console.error('polymer-xref.js is out of date - run: node scripts/build-xref.js');
    process.exit(1);
  }
  console.log('polymer-xref OK - ' + Object.keys(xref).length + ' cross-referenced (' +
    tHits + ' thermal, ' + cHits + ' chain).');
} else {
  fs.writeFileSync(outPath, body);
  console.log('polymer-xref.js written - ' + Object.keys(xref).length + ' entries (' +
    tHits + ' thermal, ' + cHits + ' chain), ' + Math.round(body.length / 1024) + ' KB.');
}
